/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ForksRouteImport } from './routes/forks'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainersUsernameRouteImport } from './routes/trainers.$username'
import { Route as QueriesQueryIdRouteImport } from './routes/queries.$queryId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ForksRoute = ForksRouteImport.update({
  id: '/forks',
  path: '/forks',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainersUsernameRoute = TrainersUsernameRouteImport.update({
  id: '/trainers/$username',
  path: '/trainers/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const QueriesQueryIdRoute = QueriesQueryIdRouteImport.update({
  id: '/queries/$queryId',
  path: '/queries/$queryId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/favorites': typeof FavoritesRoute
  '/forks': typeof ForksRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/queries/$queryId': typeof QueriesQueryIdRoute
  '/trainers/$username': typeof TrainersUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/favorites': typeof FavoritesRoute
  '/forks': typeof ForksRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/queries/$queryId': typeof QueriesQueryIdRoute
  '/trainers/$username': typeof TrainersUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/favorites': typeof FavoritesRoute
  '/forks': typeof ForksRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/queries/$queryId': typeof QueriesQueryIdRoute
  '/trainers/$username': typeof TrainersUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/dashboard'
    | '/discover'
    | '/favorites'
    | '/forks'
    | '/library'
    | '/login'
    | '/queries/$queryId'
    | '/trainers/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/dashboard'
    | '/discover'
    | '/favorites'
    | '/forks'
    | '/library'
    | '/login'
    | '/queries/$queryId'
    | '/trainers/$username'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/dashboard'
    | '/discover'
    | '/favorites'
    | '/forks'
    | '/library'
    | '/login'
    | '/queries/$queryId'
    | '/trainers/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  DashboardRoute: typeof DashboardRoute
  DiscoverRoute: typeof DiscoverRoute
  FavoritesRoute: typeof FavoritesRoute
  ForksRoute: typeof ForksRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  QueriesQueryIdRoute: typeof QueriesQueryIdRoute
  TrainersUsernameRoute: typeof TrainersUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forks': {
      id: '/forks'
      path: '/forks'
      fullPath: '/forks'
      preLoaderRoute: typeof ForksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainers/$username': {
      id: '/trainers/$username'
      path: '/trainers/$username'
      fullPath: '/trainers/$username'
      preLoaderRoute: typeof TrainersUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queries/$queryId': {
      id: '/queries/$queryId'
      path: '/queries/$queryId'
      fullPath: '/queries/$queryId'
      preLoaderRoute: typeof QueriesQueryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  DashboardRoute: DashboardRoute,
  DiscoverRoute: DiscoverRoute,
  FavoritesRoute: FavoritesRoute,
  ForksRoute: ForksRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  QueriesQueryIdRoute: QueriesQueryIdRoute,
  TrainersUsernameRoute: TrainersUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
