#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep -E '\.(ts|tsx|js|jsx|json|css|scss|md|html|yml|yaml)$')

if [ -z "$STAGED_FILES" ]; then
	exit 0
fi

echo "$STAGED_FILES" | xargs npx --prefix backend prettier --write || exit 1
echo "$STAGED_FILES" | xargs git add || exit 1
